# Generated by Django 5.2.4 on 2025-07-05 06:50

from django.db import migrations, models


def migrate_completed_to_status(apps, schema_editor):
    """Migra los datos del campo completed al campo status."""
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        if task.completed:
            task.status = 'completed'
        else:
            task.status = 'pending'
        task.save()


def reverse_migrate_status_to_completed(apps, schema_editor):
    """Revierte la migración del campo status al campo completed."""
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.all():
        task.completed = task.status == 'completed'
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        # Paso 1: Agregar el campo status
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completada')], 
                default='pending', 
                max_length=15, 
                verbose_name='Estado'
            ),
        ),
        # Paso 2: Migrar los datos del campo completed al campo status
        migrations.RunPython(
            migrate_completed_to_status,
            reverse_migrate_status_to_completed,
        ),
        # Paso 3: Actualizar las opciones de acción en TaskActivity
        migrations.AlterField(
            model_name='taskactivity',
            name='action',
            field=models.CharField(
                choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('in_progress', 'En Proceso'), ('completed', 'Completada'), ('reopened', 'Reabierta'), ('commented', 'Comentada'), ('file_added', 'Archivo añadido'), ('file_removed', 'Archivo eliminado')], 
                max_length=20, 
                verbose_name='Acción'
            ),
        ),
    ] 