# Generated by Django 5.2.4 on 2025-07-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_profile'),
    ]

    operations = [
    ]
